modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues_url}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "${author}"
logoFile = "${logo_file}"
displayURL = "${home_url}"
logoBlur = false

[[dependencies.${ id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ id }]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://modrinth.com/mod/yacl"
