minecraft_version=1.20.6
loader_version=0.19.3
fabric_version=0.100.8+1.20.6
forge_version=1.20.4-50.2.0
neoforge_version=20.6.139
mod.modmenu_version=10.0.0
mod.yacl_version=3.6.6+1.20.6
mod.modernui_core_version=3.11.1
mod.modernui_markdown_version=3.11.1
mod.modernui_loader_version=1.20.6-3.11.1.8
mod.forgeconfigapiport_version=20.6.1
